"""create rate limit table

Revision ID: 094904a332cd
Revises: 737f3547023f
Create Date: 2026-06-30 13:57:29.205024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094904a332cd'
down_revision = '737f3547023f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['backend_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit')
    # ### end Alembic commands ###
