"""create security logs table

Revision ID: 737f3547023f
Revises: 77536ab82af0
Create Date: 2026-06-23 18:47:22.041174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737f3547023f'
down_revision = '77536ab82af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['backend_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_logs')
    # ### end Alembic commands ###
