"""Create backend registration table

Revision ID: 77536ab82af0
Revises: aa27eea32c2f
Create Date: 2026-06-21 11:26:55.852678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77536ab82af0'
down_revision = 'aa27eea32c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backend_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backend_registration_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_backend_registration_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backend_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backend_registration_user_id'))
        batch_op.drop_index(batch_op.f('ix_backend_registration_api_key'))

    op.drop_table('backend_registration')
    # ### end Alembic commands ###
